version: '2'
services:
    propsybackendv01-app:
        image: propsybackendv01
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://propsybackendv01-mysql:3306/propsybackendv01?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    propsybackendv01-mysql:
        extends:
            file: mysql.yml
            service: propsybackendv01-mysql
